[project]
name = "mlscripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"

dependencies = [
    "scikit-learn>=1.7,<1.8",
    "tsai>=1.0.1",
    "tinygrad>=0.12.0",

    "torch>=2.12,<2.13",
    "torchvision>=0.27,<0.28",

    "pandas>=2.2.0",
    "pyarrow>=18.0.0",
    "xgboost>=2.1.0",
    "matplotlib>=3.9.0",
    "umap-learn>=0.5.7",
    "jupyter>=1.1.0",
    "ipykernel>=6.29.0",
    "seaborn>=0.13.2",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

torchvision = [
    { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
